remote_theme: yaoyao-liu/minimal-light
lang: zh-cmn-Hans
title: Zihua Si
title_zh: 思子华
position: Postgraduate
position_zh: 研究生
affiliation: Renmin University of China
affiliation_zh: 中国人民大学
email: zihua_si (at) ruc.edu.cn
google_scholar: https://scholar.google.com/citations?hl=zh-CN&user=JZHTkL0AAAAJ
# semantic_scholar: https://www.semanticscholar.org/author/Zihua-Si/2153850397
github_link: https://github.com/Ethan00Si
# linkedin: https://www.linkedin.com/
avatar: ./assets/img/me.png
google_analytics: G-97CPTDB0HG

## LOGO in light mode
favicon: ./assets/img/favicon.JPG
## LOGO in dark mode
favicon_dark: ./assets/img/favicon.JPG

description: Welcome to homepage of Zihua Si.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light

canonical: https://ethan00si.github.io

future: True
base_url: https://ethan00si.github.io
# base_url : http://127.0.0.1:4000  # debug in local

timezone: Asia/Shanghai



