remote_theme: yaoyao-liu/minimal-light
lang: zh-cmn-Hans
title: Zihua Si
position: Undergraduate
affiliation: Renmin University of China
email: 2018202181 (at) ruc.edu.cn
# google_scholar: https://scholar.google.com/
github_link: https://github.com/Ethan00Si
# linkedin: https://www.linkedin.com/
avatar: ./assets/img/me.png
# google_analytics: UA-111540567-4

## LOGO in light mode
favicon: ./assets/img/favicon.JPG
## LOGO in dark mode
favicon_dark: ./assets/img/favicon.JPG

description: Welcome to homepage of Zihua Si.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
