remote_theme: yaoyao-liu/minimal-light
lang: zh-cmn-Hans
title: Zihua Si
title_zh: 思子华
position: Undergraduate
position_zh: 本科生
affiliation: Renmin University of China
affiliation_zh: 中国人民大学
email: 2018202181 (at) ruc.edu.cn
# google_scholar: https://scholar.google.com/
github_link: https://github.com/Ethan00Si
# linkedin: https://www.linkedin.com/
avatar: ./assets/img/me.png
google_analytics: G-97CPTDB0HG

## LOGO in light mode
favicon: ./assets/img/favicon.JPG
## LOGO in dark mode
favicon_dark: ./assets/img/favicon.JPG

description: Welcome to homepage of Zihua Si.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light

future: True
base_url : https://ethan00si.github.io/zihua_si.github.io/
# base_url : http://127.0.0.1:4000  # debug in local

timezone: Asia/Shanghai